services:
  - type: web
    name: werewolveshx
    env: node
    nodeVersion: 18
    buildCommand: npm install && npm run build && npm run migrate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://werewolveshx_user:XYSXU8irIWITF1Fv0wmCuMuXeoHbzoIw@dpg-d1qg0mre5dus73e7hv6g-a/werewolveshx
