services:
  - type: web
    name: werewolveshx
    env: node
    nodeVersion: 18
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
