services:
  - type: web
    name: werewolveshx
    env: node
    buildCommand: npm install -g vite && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
