services:
  - type: web
    name: werewolveshx
    env: node
    nodeVersion: 20.11.0
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://werewolveshx_user:XYSXU8irIWITF1Fv0wmCuMuXeoHbzoIw@dpg-d1qg0mre5dus73e7hv6g-a.frankfurt-postgres.render.com/werewolveshx
      - key: PORT
        value: "10000"
      - key: SESSION_SECRET
        sync: false
      - key: VITE_API_URL
        value: "https://werewolveshx.onrender.com"
    healthCheckPath: /api/health
    postDeployCommand: npm run migrate
